-- your code here
INSERT INTO users(name, age) VALUES ('Richard', 40);
INSERT INTO users(name, age) VALUES ('Al', 44);
INSERT INTO users(name, age) VALUES ('Michael', 31);
INSERT INTO users(name, age) VALUES ('Josh', 27);
INSERT INTO users(name, age) VALUES ('Ziggy', 46);
INSERT INTO users(name, age) VALUES ('Brian', 54);
INSERT INTO users(name, age) VALUES ('Changhi', 24);
INSERT INTO users(name, age) VALUES ('Luigi', 38);
INSERT INTO users(name, age) VALUES ('Alan', 50);
INSERT INTO users(name, age) VALUES ('James', 24);
INSERT INTO users(name, age) VALUES ('Ryan', 32);
INSERT INTO users(name, age) VALUES ('Richard', 43);
INSERT INTO users(name, age) VALUES ('Al', 34);
INSERT INTO users(name, age) VALUES ('Michael', 41);
INSERT INTO users(name, age) VALUES ('Josh', 17);
INSERT INTO users(name, age) VALUES ('Ziggy', 66);
INSERT INTO users(name, age) VALUES ('Brian', 34);
INSERT INTO users(name, age) VALUES ('Changhi', 14);
INSERT INTO users(name, age) VALUES ('Luigi', 78);
INSERT INTO users(name, age) VALUES ('Alan', 53);

INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('LTD', 'Gaming', 1000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('Kudos', 'Service', 30000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('MobilePedia', 'Education', 50000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('TDTHP', 'Service', 10000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('LTD Craps', 'Gaming', 5000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('LTD', 'Gaming', 1000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('LTD', 'Gaming', 1000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('LTD', 'Gaming', 1000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('LTD', 'Gaming', 1000, '2007-01-01', '2008-01-01');
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ('LTD', 'Gaming', 1000, '2007-01-01', '2008-01-01');

-- INSERT INTO projects(title, category, funding_goal) VALUES ('Kudos', 'Service', 30000);
-- INSERT INTO projects(title, category, funding_goal) VALUES ('MobilePedia', 'Education', 50000)
-- INSERT INTO projects(title, category, funding_goal) VALUES ('TDTHP', 'Service', 10000);
-- INSERT INTO projects(title, category, funding_goal) VALUES ('LTD Craps', 'Gaming', 5000);
-- INSERT INTO projects(title, category, funding_goal) VALUES ('Yelp', 'Service', 1000000);
-- INSERT INTO projects(title, category, funding_goal) VALUES ('Kickstarter', 'Service', 50000);
-- INSERT INTO projects(title, category, funding_goal) VALUES ('Instagram', 'Photo', 5000000);
-- INSERT INTO projects(title, category, funding_goal) VALUES ('LTD Blackjack', 'Gaming', 500);
-- INSERT INTO projects(title, category, funding_goal) VALUES ('MyFace', 'Service', 100);

INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (125, 1, 1);